# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       madeo-uplayer
Summary:    Madeo MUMS uplayer
Version:    0.1.1
Release:    1
Group:      System/X11
License:    LGPLv2
URL:        https://github.com/arfoll/Madeo-MUMS-player
Source0:    madeo-uplayer-%{version}.tar.bz2
Source100:  madeo-uplayer.yaml


%description
Uplayer is the Madeo implementation for a MUMS player in MeeGo




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}%{_bindir}/ .%{_initrddir}
install -m 755 madeo-uplayer %{buildroot}%{_bindir}/madeo-uplayer
install -p -m755 madeo-uplayer.init .%{_initrddir}/madeo-uplayer
# << install pre

# >> install post
# << install post






%files
%defattr(-,root,root,-)
%doc README TODO LICENSE
%{_bindir}/madeo-uplayer
# >> files
# << files


