# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       madeo-uplayer
Summary:    Madeo MUMS uplayer
Version:    0.1.1
Release:    1
Group:      System/X11
License:    LGPLv2
BuildArch:  noarch
URL:        https://github.com/arfoll/Madeo-MUMS-player
Source0:    madeo-uplayer-%{version}.tar.bz2
Source100:  madeo-uplayer.yaml
Requires(post): /sbin/service
Requires(post): /sbin/chkconfig
Requires(postun): /sbin/service
Requires(postun): /sbin/chkconfig


%description
Uplayer is the Madeo implementation for a MUMS player in MeeGo




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}%{_bindir}/ %{buildroot}%{_initrddir}/
install -m 755 madeo-uplayer %{buildroot}%{_bindir}/madeo-uplayer
install -p -m 755 madeo-uplayer.init %{buildroot}%{_initrddir}/madeo-uplayer
# << install pre

# >> install post
%preun
if [ "$1" -eq 0 ]; then
/sbin/service madeo-uplayer stop &> /dev/null
/sbin/chkconfig --del madeo-uplayer
fi
:

%postun
if [ "$1" -ge 1 ]; then
/sbin/service madeo-uplayer condrestart &> /dev/null
fi
:
# << install post






%files
%defattr(-,root,root,-)
%doc README TODO LICENSE
%{_bindir}/madeo-uplayer
%{_initrddir}/madeo-uplayer
# >> files
# << files


